task: mcqa
dataset: __DATASET__
model: bert_text_cls
model_name_or_path: __MODEL__
do_train: true
do_eval: true
training:
  output_dir: __OUTPUT_DIR__
  num_train_epochs: 5
  per_device_train_batch_size: 6
  per_device_eval_batch_size: 6
  learning_rate: 2e-5
  warmup_steps: 0
  logging_steps: 100
  eval_steps: 500
  save_steps: 500
  seed: 42
  fp16: true
