task: ner_span
dataset: __DATASET__
model: bert_token_ner
model_name_or_path: __MODEL__
do_train: true
do_eval: true
training:
  output_dir: __OUTPUT_DIR__
  num_train_epochs: 10
  per_device_train_batch_size: 16
  per_device_eval_batch_size: 32
  learning_rate: 2e-5
  warmup_steps: 100
  logging_steps: 50
  eval_steps: 100
  save_steps: 100
  save_total_limit: 2
  load_best_model_at_end: true
  seed: 42
  metric_for_best_model: eval_loss
  greater_is_better: false
  early_stopping_patience: 3
  bf16: true
