description: "Eval DECAY_MODEL_NAME (DIAMED + FRASIMED + MedDialog)"
seeds: [42, 43, 44, 45, 46]

datasets:
  cls: [diamed, frasimed_cantemist_norm, frasimed_distemist_norm_top100]
  multilabel: [meddialog_women]

model_groups:
  eval:
    configs:
      cls: /lustre/fswork/projects/rech/rua/uvb79kr/tabib/configs/base/cls_bert.yaml
      multilabel: /lustre/fswork/projects/rech/rua/uvb79kr/tabib/configs/base/multilabel_bert.yaml
    models:
      DECAY_MODEL_NAME: HF_MODEL_PATH

output:
  json: /lustre/fswork/projects/rech/rua/uvb79kr/tabib/results/decay-merge/results_DECAY_MODEL_NAME.json
  markdown: /lustre/fswork/projects/rech/rua/uvb79kr/tabib/results/decay-merge/results_DECAY_MODEL_NAME.md
