description: DrBenchmark - French Biomedical NLP with BERT Models

datasets:
  ner_token: [quaero_emea_token, quaero_medline_token, e3c_token, cas1_token, cas2_token]
  cls: [essai, diamed, fracco_icd_classification]
  multilabel: [morfitt, meddialog_women]
  sim: [clister]
  mcqa: [mediqal_mcqm, mediqal_mcqu, french_med_mcqa_extended]

model_groups:
  bert:
    configs:
      ner_token: base/ner_token_bert.yaml
      cls: base/cls_bert.yaml
      multilabel: base/multilabel_bert.yaml
      sim: base/sim_bert.yaml
      mcqa: base/mcqa_bert.yaml
    models:
      camembert: camembert-base
      camembert-bio: almanach/camembert-bio-base
      camembertv2: almanach/camembertv2-base
      camembertv2-bio: rntc/camembertv2-bio-edu_gt3
      moderncamembert: almanach/moderncamembert-base
      drbert: Dr-BERT/DrBERT-7GB
      bioclinical-modernbert: thomas-sounack/BioClinical-ModernBERT-base
      camembert-enriched: rntc/camembert-enriched-v4-full-enriched-v4-full-no_other_scores_ge2

output:
  json: ../results/bert_drbenchmark.json
  markdown: ../results/bert_drbenchmark.md
  wandb:
    project: tabib-drbenchmark
    table: bert_results
