task: ner_span
dataset: emea
model: vllm_ner
model_name_or_path: google/medgemma-27b-text-it
do_train: false
do_eval: true
preprocessing:
  type: sentence_chunker
  max_tokens: 512
backend_args:
  use_chat: true
  tensor_parallel_size: 1
  gpu_memory_utilization: 0.9
  max_tokens: 2048
  num_few_shot: 5
  kv_cache_dtype: fp8
  dtype: bfloat16
