task: ner_span
dataset: cas2
model: vllm_ner
model_name_or_path: Qwen/Qwen3-32B
do_train: false
do_eval: true
preprocessing:
  type: sentence_chunker
  max_tokens: 2048
backend_args:
  use_chat: true
  tensor_parallel_size: 1
  gpu_memory_utilization: 0.95
  max_tokens: 8192
  num_few_shot: 3
  # dtype: bfloat16
  quantization: fp8
