task: ner_span
dataset: cas1
model: vllm_ner
model_name_or_path: utter-project/EuroLLM-9B
do_train: false
do_eval: true
preprocessing:
  type: sentence_chunker
  max_tokens: 2048
backend_args:
  use_chat: false
  tensor_parallel_size: 1
  gpu_memory_utilization: 0.9
  max_tokens: 8192
  num_few_shot: 0
  dtype: bfloat16
