task: ner_span
dataset: cas2
model: vllm_ner
model_name_or_path: almanach/Gaperon-1125-8B
do_train: false
do_eval: true
preprocessing:
  type: sentence_chunker
  max_tokens: 512
backend_args:
  use_chat: false
  tensor_parallel_size: 1
  gpu_memory_utilization: 0.9
  max_tokens: 8192
  num_few_shot: 3
